### ISSUE TITLE
How to use in .vue component?

### ISSUE THREAD

**Issue by rmx90210** [airyland/vue-config#1]
I've been puzzling over how to globally expose my config so this plugin looks super useful. One question -- how would I go about using it in a `.vue` component? For example:

```
<script>
  console.log(this.$config);
</script>
```

prints `undefined`.

Any pointers? Thanks!

**Comment by airyland** [comment]
you should use the code inside vue instance

``` js
created () {
  console.log(this.$config)
},
methods: {
  getConfig () {
   console.log(this.$config)
  }
}
```
